spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: dbuser
    password: dbpassword
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect