DROP TABLE IF EXISTS users;

CREATE TABLE users (
  username VARCHAR(100) NOT NULL PRIMARY KEY,
  password VARCHAR(200) NOT NULL
);

CREATE TABLE roles (
  USERNAME VARCHAR(50) NOT NULL,
  role VARCHAR(68) NOT NULL,
  FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);
